print("========================")
print("||                    ||")
print("||   Rózsás Viktor    ||")
print("||                    ||")
print("||   10b              ||")
print("||                    ||")
print("||   2023.09.07       ||")
print("||                    ||")
print("========================")
